# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hospital_pb2 as hospital__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hospital_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HospitalServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPatientRecord = channel.unary_unary(
                '/hospital.HospitalService/GetPatientRecord',
                request_serializer=hospital__pb2.PatientRequest.SerializeToString,
                response_deserializer=hospital__pb2.PatientResponse.FromString,
                _registered_method=True)
        self.AddMedicalReport = channel.unary_unary(
                '/hospital.HospitalService/AddMedicalReport',
                request_serializer=hospital__pb2.ReportRequest.SerializeToString,
                response_deserializer=hospital__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.CheckDoctorAvailability = channel.unary_unary(
                '/hospital.HospitalService/CheckDoctorAvailability',
                request_serializer=hospital__pb2.DoctorRequest.SerializeToString,
                response_deserializer=hospital__pb2.DoctorResponse.FromString,
                _registered_method=True)


class HospitalServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetPatientRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMedicalReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDoctorAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HospitalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPatientRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientRecord,
                    request_deserializer=hospital__pb2.PatientRequest.FromString,
                    response_serializer=hospital__pb2.PatientResponse.SerializeToString,
            ),
            'AddMedicalReport': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMedicalReport,
                    request_deserializer=hospital__pb2.ReportRequest.FromString,
                    response_serializer=hospital__pb2.ReportResponse.SerializeToString,
            ),
            'CheckDoctorAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDoctorAvailability,
                    request_deserializer=hospital__pb2.DoctorRequest.FromString,
                    response_serializer=hospital__pb2.DoctorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hospital.HospitalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hospital.HospitalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HospitalService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPatientRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.HospitalService/GetPatientRecord',
            hospital__pb2.PatientRequest.SerializeToString,
            hospital__pb2.PatientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMedicalReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.HospitalService/AddMedicalReport',
            hospital__pb2.ReportRequest.SerializeToString,
            hospital__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckDoctorAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hospital.HospitalService/CheckDoctorAvailability',
            hospital__pb2.DoctorRequest.SerializeToString,
            hospital__pb2.DoctorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
