# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hospital.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hospital.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehospital.proto\x12\x08hospital\"$\n\x0ePatientRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\"U\n\x0fPatientResponse\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x13\n\x0b\x62lood_group\x18\x04 \x01(\t\";\n\rReportRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x16\n\x0ereport_details\x18\x02 \x01(\t\"2\n\x0eReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\rDoctorRequest\x12\x11\n\tdoctor_id\x18\x01 \x01(\t\"S\n\x0e\x44octorResponse\x12\x13\n\x0b\x64octor_name\x18\x01 \x01(\t\x12\x14\n\x0cis_available\x18\x02 \x01(\x08\x12\x16\n\x0e\x61vailable_time\x18\x03 \x01(\t2\xf5\x01\n\x0fHospitalService\x12I\n\x10GetPatientRecord\x12\x18.hospital.PatientRequest\x1a\x19.hospital.PatientResponse\"\x00\x12G\n\x10\x41\x64\x64MedicalReport\x12\x17.hospital.ReportRequest\x1a\x18.hospital.ReportResponse\"\x00\x12N\n\x17\x43heckDoctorAvailability\x12\x17.hospital.DoctorRequest\x1a\x18.hospital.DoctorResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hospital_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PATIENTREQUEST']._serialized_start=28
  _globals['_PATIENTREQUEST']._serialized_end=64
  _globals['_PATIENTRESPONSE']._serialized_start=66
  _globals['_PATIENTRESPONSE']._serialized_end=151
  _globals['_REPORTREQUEST']._serialized_start=153
  _globals['_REPORTREQUEST']._serialized_end=212
  _globals['_REPORTRESPONSE']._serialized_start=214
  _globals['_REPORTRESPONSE']._serialized_end=264
  _globals['_DOCTORREQUEST']._serialized_start=266
  _globals['_DOCTORREQUEST']._serialized_end=300
  _globals['_DOCTORRESPONSE']._serialized_start=302
  _globals['_DOCTORRESPONSE']._serialized_end=385
  _globals['_HOSPITALSERVICE']._serialized_start=388
  _globals['_HOSPITALSERVICE']._serialized_end=633
# @@protoc_insertion_point(module_scope)
